" Mac remap
      nmap ˙ <A-h>
      nmap ∆ <A-j>
      nmap ˚ <A-k>
      nmap ¬ <A-l>
      nmap Ø <A-O>
      nmap ø <A-o>
      nmap π <A-p>
      nmap – <A-->
      nmap ≠ <A-=>
      nmap º <A-0>
      nmap ¡ <A-1>
      nmap ™ <A-2>
      nmap £ <A-3>
      nmap ¢ <A-4>
